### PR TITLE
Corrected wrong syntax for user_idnum variable value substitution

### PR DESCRIPTION
**Pull request by onkardahale**
Screenshot 2024-04-17 at 10 49 07 AM

現状の不具合

### CODE REVIEW

**Comment by onkardahale** [comment]
@fumihax PRをレビューしていただけますか?

**Review by fumihax — APPROVED** [review]
thanks very much!

**Review by fumihax — APPROVED** [review]
thanks!

**Review by fumihax — APPROVED** [review]

**Comment by fumihax** [comment]
I'm sorry ... 
I'm new to github, so I don't really know how to merge...

**Comment by fumihax** [comment]
thanks.
The merge is done.

**Pull request merged**
